### ISSUE TITLE
compatibility

### ISSUE THREAD

**Issue by MHz-Git** [zirafa/pushtape-player.js#1]
Is this compatible with Drupal sites not created using the Pushtape distribution?

How would this be implemented on a Drupal site with soundmanager2 that was not created with Pushtape?

**Comment by zirafa** [comment]
Yes, it is compatible with Drupal sites not using the Pushtape distribution. I've made a Drupal module to make it easier to integrate into sites. You can install this module without installing the entire distribution.

Please see: http://www.drupal.org/project/pushtape_player

Hope to have a stable release for it out fairly soon.

**Comment by zirafa** [comment]
Pushtape player is now available on Drupal.org for easier integration.
