### ISSUE TITLE
Play button that plays the playlist always from the start.

### ISSUE THREAD

**Issue by hennysmafter** [zirafa/pushtape-player.js#2]
Dear Farsheed Zirafa, I love this so much! It helped me a lot in making a audio composer but I am missing one function. Which is to have a play button that always plays the entire playlist from the beginning. 

Because when you look at your demo(link below) you can see that when it has played the last number when you press play again it will play that number instead of returning to the beginning of the list. 
http://zirafa.github.io/pushtape-player.js/demo/autoscan-example.html 

So I would really like to have another button that if clicked always starts playing at the first item of the playlist. If this is already possible then please tell me how.

Thanks for all the hard work you have put into this and thanks in advance for helping.

**Comment by zirafa** [comment]
Hey there, when the last track in a playlist is played, if repeatAll is set to true it will loop back and start playing from the beginning again. Is that the feature you are looking for? If not I'd like to better understand what you are looking for (perhaps something like a "reset" button?)

**Comment by zirafa** [comment]
Hi Hennysmafter, I think I now understand the problem you were encountering. Please take a look at the recent commits, there is now a playAll button you can use for the behavior you are looking for.

## Example template for playAll button

```
      <a class="pt-play-all" href="#" title="Play All">
        <span class="play-btn"><span class="pt-play-icon">▶</span></span>
        <span class="pause-btn"><span class="pt-pause-icon">❚❚</span></span>
      </a>
```

The optional "Play All" button differs from the more global "Play Pause" button in the following ways:
- If the last track in the playlist ends, pressing "Play All" will restart the playlist from the beginning, not replay the last track.
- If audio is playing that isn't in the page playlist, "Play All" is not aware of it. If pressed it will just play the first track in the playlist.
- If audio is playing and it exists in the page playlist, "Play All" and "Play Pause" will behave similarly.
