### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by Fliktrax** [zirafa/pushtape-player.js#5]
Could be my current SM version or trival, but I'm getting the following console error. This error only outputs upon PT Player initialization. Keyboard control (i.e. spacebar control) works after first track played in playlist

soundmanager2.js:4326 soundManager.setup(): Could not find option "keyboardControl"
complain @ soundmanager2.js:4326
pushtape-player.js:560 Uncaught ReferenceError: oControl is not defined
    at HTMLDocument.PushtapePlayer.keyboardToggle (pushtape-player.js:560)
pushtape-player.js:560 Uncaught ReferenceError: oControl is not defined
    at HTMLDocument.PushtapePlayer.keyboardToggle (pushtape-player.js:560)
pushtape-player.js:560 Uncaught ReferenceError: oControl is not defined
    at HTMLDocument.PushtapePlayer.keyboardToggle (pushtape-player.js:560)

Additionally, the following console errors occur on player focus (i.e. click player timeline). Again, these errors only appear upon player initialization:

Uncaught TypeError: Cannot read property 'pause' of null
    at HTMLDocument.PushtapePlayer.handleMouseDown (pushtape-player.js:543)
PushtapePlayer.handleMouseDown @ pushtape-player.js:543

Uncaught TypeError: Cannot read property 'resume' of null
    at HTMLDocument.PushtapePlayer.stopDrag (pushtape-player.js:613)
PushtapePlayer.stopDrag @ pushtape-player.js:613

**Comment by zirafa** [comment]
Huh, I haven't seen these types of errors before, thanks. Can you paste the code you are using to initialize PushtapePlayer?

**Comment by Fliktrax** [comment]
Hi Farsheed,

Here's the initialization code that I'm using:

```var pushtapePlayer = null;

soundManager.setup({
  debugMode: false,
  url: 'swf/',
  useHighPerformance: false,
  preferFlash: false,
  flashVersion: 9,
  wmode: 'transparent',
  onready: function() {
    pushtapePlayer = new PushtapePlayer();
    pushtapePlayer.init({
      playNext: true,
      autoPlay: false,
      repeatAll: false,
      keyboardControl: true,
    });
  },
  ontimeout: function() {
    //console.log('Error initializing the Pushtape player.');
  }
});
```

Again, the following errors (in Chrome console
![spacebar_error](https://user-images.githubusercontent.com/21086929/28370718-f993f4e2-6c68-11e7-838b-82e3509e3e80.jpg)
![timeline_click_error](https://user-images.githubusercontent.com/21086929/28370717-f993e786-6c68-11e7-8aaa-a6e7670e6592.png)

) only appear after PT player initialization when the spacebar is pressed, or the user clicks in the timeline container , and no other sound file is playing:

Here is an example:
http://frederator.fliktrax.com/ft-details/?pos=s2&topic=category&detail=action-adventure
Username: zirafa
Password: test

**Comment by zirafa** [comment]
Thanks for the detailed bug report! I just pushed a fix for these errors to master -- hopefully that resolves the issue for you.

**Comment by Fliktrax** [comment]
Hi Farsheed! That definitely resolved the issue! Thanks much and thank you for the excellent player! Saved me much dev time over the years .... Cheers
